# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('camera', models.CharField(choices=[('Canon', 'Canon'), ('Nikon', 'Nikon'), ('Olympus', 'Olympus'), ('Sony', 'Sony'), ('Fujifilm', 'Fujifilm')], max_length=120)),
                ('services', models.CharField(choices=[('Port', 'Portrait'), ('Wild', 'Wildlife'), ('Film', 'Film'), ('BW', 'Black & White'), ('Other', 'Other')], max_length=300)),
                ('bio', models.CharField(max_length=700)),
                ('phone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
