# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171205_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
