# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_auto_20171205_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='camera',
            field=models.CharField(blank=True, choices=[('Canon', 'Canon'), ('Nikon', 'Nikon'), ('Olympus', 'Olympus'), ('Sony', 'Sony'), ('Fujifilm', 'Fujifilm')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='services',
            field=models.CharField(blank=True, choices=[('Port', 'Portrait'), ('Wild', 'Wildlife'), ('Film', 'Film'), ('BW', 'Black & White'), ('Other', 'Other')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
