# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='cover-images'),
        ),
    ]
