# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20171201_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
