# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20171201_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover-images'),
        ),
    ]
